### ISSUE TITLE
how to build 

### ISSUE THREAD

**Issue by dananothername** [BTTRG/recsbr#1]
i pasted the command you offered 
![Screenshot_2022-11-26_05-23-31](https://user-images.githubusercontent.com/101902085/204083948-223f4571-d040-4f6a-8ad6-4ab0ed730b07.png)
i don't know much about cmake
can you tell the next step

**Comment by BTTRG** [comment]
oopsied

**Comment by dananothername** [comment]
yes I can see 
to what distro you set it up
and upload it here ,all ubuntu work the same

**Comment by BTTRG** [comment]
I don't understand what you mean. The mod should build for Windows, Mac, and Linux, and it shouldn't matter what distro you use.
I'm not going to provide you with tech support, you need to figure out how to fix the issue yourself. If you can't, you're probably not ready for Linux.

**Comment by dananothername** [comment]
what did you use to create the source code 
this would guide me to ask the right guy

**Comment by luRaichu** [comment]
You only generated build files for the game, which you generally only need to do the first time you're compiling for a specific platform. You need to run `cmake --build build --config Release` to finish compiling the game.
